/* Generated By:JJTree: Do not edit this line. Additive.java */

package com.fatdog.xmlEngine.javacc;

public class Additive extends SimpleNode {
  public Additive(int id) {
    super(id);
  }

  public Additive(XQueryParser p, int id) {
    super(p, id);
  }

}
