/* Generated By:JJTree: Do not edit this line. DefaultNamespaceDecl.java */

package com.fatdog.xmlEngine.javacc;

public class DefaultNamespaceDecl extends SimpleNode {
  public DefaultNamespaceDecl(int id) {
    super(id);
  }

  public DefaultNamespaceDecl(XQueryParser p, int id) {
    super(p, id);
  }

}
