/* Generated By:JJTree: Do not edit this line. DoubleLit.java */

package com.fatdog.xmlEngine.javacc;

public class DoubleLit extends SimpleNode {
  public DoubleLit(int id) {
    super(id);
  }

  public DoubleLit(XQueryParser p, int id) {
    super(p, id);
  }

}
