/* Generated By:JJTree: Do not edit this line. IfThenElse.java */

package com.fatdog.xmlEngine.javacc;

public class IfThenElse extends SimpleNode {
  public IfThenElse(int id) {
    super(id);
  }

  public IfThenElse(XQueryParser p, int id) {
    super(p, id);
  }

}
