/* Generated By:JJTree: Do not edit this line. Multiplicative.java */

package com.fatdog.xmlEngine.javacc;

public class Multiplicative extends SimpleNode {
  public Multiplicative(int id) {
    super(id);
  }

  public Multiplicative(XQueryParser p, int id) {
    super(p, id);
  }

}
