/* Generated By:JJTree: Do not edit this line. NamespaceDecl.java */

package com.fatdog.xmlEngine.javacc;

public class NamespaceDecl extends SimpleNode {
  public NamespaceDecl(int id) {
    super(id);
  }

  public NamespaceDecl(XQueryParser p, int id) {
    super(p, id);
  }

}
