/* Generated By:JJTree: Do not edit this line. Unary.java */

package com.fatdog.xmlEngine.javacc;

public class Unary extends SimpleNode {
  public Unary(int id) {
    super(id);
  }

  public Unary(XQueryParser p, int id) {
    super(p, id);
  }

}
