/* Generated By:JJTree&JavaCC: Do not edit this line. XQueryParserConstants.java */
package com.fatdog.xmlEngine.javacc;

public interface XQueryParserConstants {

  int EOF = 0;
  int Pragma = 1;
  int MUExtension = 2;
  int ExtensionStart = 3;
  int ExprCommentStart = 4;
  int PragmaContents = 5;
  int ExtensionContents = 6;
  int ExprCommentContent = 7;
  int ExtensionEnd = 8;
  int ExprCommentEnd = 9;
  int PragmaKeyword = 10;
  int Extension = 11;
  int XmlCommentStart = 12;
  int XmlCommentEnd = 13;
  int IntegerLiteral = 14;
  int DecimalLiteral = 15;
  int DoubleLiteral = 16;
  int StringLiteral = 17;
  int StringLiteralForKindTest = 18;
  int VersionStringLiteral = 19;
  int AtStringLiteral = 20;
  int DeclareDefaultNamespace = 21;
  int URLLiteral = 22;
  int ModuleNamespace = 23;
  int skip_ = 25;
  int NotOccurrenceIndicator = 26;
  int S = 27;
  int ProcessingInstructionStart = 28;
  int ProcessingInstructionEnd = 29;
  int AxisChild = 30;
  int AxisDescendant = 31;
  int AxisParent = 32;
  int AxisAttribute = 33;
  int AxisSelf = 34;
  int AxisDescendantOrSelf = 35;
  int AxisAncestor = 36;
  int AxisFollowingSibling = 37;
  int AxisPrecedingSibling = 38;
  int AxisFollowing = 39;
  int AxisPreceding = 40;
  int AxisNamespace = 41;
  int AxisAncestorOrSelf = 42;
  int DefineFunction = 43;
  int External = 44;
  int Or = 45;
  int And = 46;
  int Div = 47;
  int Idiv = 48;
  int Mod = 49;
  int Multiply = 50;
  int In = 51;
  int SchemaMode = 52;
  int SchemaModeForDeclareValidate = 53;
  int Nillable = 54;
  int DeclareValidation = 55;
  int SchemaGlobalContextSlash = 56;
  int SchemaGlobalTypeName = 57;
  int SchemaGlobalContext = 58;
  int SchemaContextStepSlash = 59;
  int SchemaContextStep = 60;
  int InContextForKindTest = 61;
  int Global = 62;
  int Satisfies = 63;
  int Return = 64;
  int Then = 65;
  int Else = 66;
  int Default = 67;
  int DeclareXMLSpace = 68;
  int DeclareBaseURI = 69;
  int XMLSpacePreserve = 70;
  int XMLSpaceStrip = 71;
  int Namespace = 72;
  int DeclareNamespace = 73;
  int To = 74;
  int Where = 75;
  int Collation = 76;
  int Intersect = 77;
  int Union = 78;
  int Except = 79;
  int As = 80;
  int AtWord = 81;
  int Case = 82;
  int Instanceof = 83;
  int Castable = 84;
  int RparAs = 85;
  int Item = 86;
  int ElementType = 87;
  int AttributeType = 88;
  int ElementQNameLbrace = 89;
  int AttributeQNameLbrace = 90;
  int NamespaceNCNameLbrace = 91;
  int PINCNameLbrace = 92;
  int PILbrace = 93;
  int CommentLbrace = 94;
  int ElementLbrace = 95;
  int AttributeLbrace = 96;
  int TextLbrace = 97;
  int DeclareCollation = 98;
  int DefaultElement = 99;
  int DeclareDefaultElement = 100;
  int DeclareDefaultFunction = 101;
  int Empty = 102;
  int ImportSchemaToken = 103;
  int ImportModuleToken = 104;
  int Nmstart = 105;
  int Nmchar = 106;
  int Star = 107;
  int AnyName = 108;
  int NCNameColonStar = 109;
  int StarColonNCName = 110;
  int Root = 111;
  int RootDescendants = 112;
  int Slash = 113;
  int SlashSlash = 114;
  int Equals = 115;
  int AssignEquals = 116;
  int Is = 117;
  int NotEquals = 118;
  int IsNot = 119;
  int LtEquals = 120;
  int LtLt = 121;
  int GtEquals = 122;
  int GtGt = 123;
  int FortranEq = 124;
  int FortranNe = 125;
  int FortranGt = 126;
  int FortranGe = 127;
  int FortranLt = 128;
  int FortranLe = 129;
  int ColonEquals = 130;
  int Lt = 131;
  int Gt = 132;
  int Minus = 133;
  int Plus = 134;
  int UnaryMinus = 135;
  int UnaryPlus = 136;
  int OccurrenceZeroOrOne = 137;
  int OccurrenceZeroOrMore = 138;
  int OccurrenceOneOrMore = 139;
  int Vbar = 140;
  int Lpar = 141;
  int At = 142;
  int Lbrack = 143;
  int Rbrack = 144;
  int Rpar = 145;
  int RparForKindTest = 146;
  int Some = 147;
  int Every = 148;
  int For = 149;
  int Let = 150;
  int CastAs = 151;
  int TreatAs = 152;
  int ValidateLbrace = 153;
  int ValidateContext = 154;
  int ValidateGlobal = 155;
  int ValidateSchemaMode = 156;
  int Digits = 157;
  int DocumentLpar = 158;
  int DocumentLparForKindTest = 159;
  int DocumentLbrace = 160;
  int NodeLpar = 161;
  int CommentLpar = 162;
  int TextLpar = 163;
  int ProcessingInstructionLpar = 164;
  int ElementTypeForDocumentTest = 165;
  int ElementTypeForKindTest = 166;
  int AttributeTypeForKindTest = 167;
  int ProcessingInstructionLparForKindTest = 168;
  int TextLparForKindTest = 169;
  int CommentLparForKindTest = 170;
  int NodeLparForKindTest = 171;
  int IfLpar = 172;
  int TypeswitchLpar = 173;
  int Comma = 174;
  int SemiColon = 175;
  int QuerySeperator = 176;
  int CommaForKindTest = 177;
  int EscapeQuot = 178;
  int OpenQuot = 179;
  int CloseQuot = 180;
  int Dot = 181;
  int DotDot = 182;
  int OrderBy = 183;
  int OrderByStable = 184;
  int Ascending = 185;
  int Descending = 186;
  int EmptyGreatest = 187;
  int EmptyLeast = 188;
  int PITarget = 189;
  int NCName = 190;
  int Prefix = 191;
  int LocalPart = 192;
  int VariableIndicator = 193;
  int VarName = 194;
  int DefineVariable = 195;
  int QNameForSequenceType = 196;
  int QNameForItemType = 197;
  int ExtensionQName = 198;
  int PragmaQName = 199;
  int QName = 200;
  int NCNameForPrefix = 201;
  int NCNameForPI = 202;
  int CdataSectionStart = 203;
  int CdataSectionEnd = 204;
  int PredefinedEntityRef = 205;
  int HexDigits = 206;
  int CharRef = 207;
  int StartTagOpen = 208;
  int StartTagOpenRoot = 209;
  int StartTagClose = 210;
  int EmptyTagClose = 211;
  int EndTagOpen = 212;
  int EndTagClose = 213;
  int ValueIndicator = 214;
  int TagQName = 215;
  int Lbrace = 216;
  int LbraceExprEnclosure = 217;
  int LCurlyBraceEscape = 218;
  int RCurlyBraceEscape = 219;
  int EscapeApos = 220;
  int OpenApos = 221;
  int CloseApos = 222;
  int Char = 223;
  int ElementContentChar = 224;
  int QuotAttContentChar = 225;
  int AposAttContentChar = 226;
  int CommentContentChar = 227;
  int PIContentChar = 228;
  int CDataSectionChar = 229;
  int Rbrace = 230;
  int WhitespaceChar = 231;
  int Letter = 232;
  int BaseChar = 233;
  int Ideographic = 234;
  int CombiningChar = 235;
  int Digit = 236;
  int Extender = 237;

  int DEFAULT = 0;
  int OPERATOR = 1;
  int NAMESPACEDECL = 2;
  int NAMESPACEKEYWORD = 3;
  int XMLSPACE_DECL = 4;
  int ITEMTYPE = 5;
  int VARNAME = 6;
  int EXPR_COMMENT = 7;
  int XML_COMMENT = 8;
  int EXT_KEY = 9;
  int ELEMENT_CONTENT = 10;
  int KINDTEST = 11;
  int KINDTESTFORPI = 12;
  int QNAME = 13;
  int OCCURRENCEINDICATOR = 14;
  int CLOSEKINDTEST = 15;
  int SCHEMACONTEXTSTEP = 16;
  int START_TAG = 17;
  int END_TAG = 18;
  int PROCESSING_INSTRUCTION_CONTENT = 19;
  int DUMMY = 20;
  int QUOT_ATTRIBUTE_CONTENT = 21;
  int PROCESSING_INSTRUCTION = 22;
  int CDATA_SECTION = 23;
  int APOS_ATTRIBUTE_CONTENT = 24;

  String[] tokenImage = {
    "<EOF>",
    "<Pragma>",
    "<MUExtension>",
    "\"(::\"",
    "\"(:\"",
    "<PragmaContents>",
    "<ExtensionContents>",
    "<ExprCommentContent>",
    "\"::)\"",
    "\":)\"",
    "\"pragma\"",
    "\"extension\"",
    "\"<!--\"",
    "\"-->\"",
    "<IntegerLiteral>",
    "<DecimalLiteral>",
    "<DoubleLiteral>",
    "<StringLiteral>",
    "<StringLiteralForKindTest>",
    "<VersionStringLiteral>",
    "<AtStringLiteral>",
    "<DeclareDefaultNamespace>",
    "<URLLiteral>",
    "<ModuleNamespace>",
    "<token of kind 24>",
    "<skip_>",
    "<NotOccurrenceIndicator>",
    "<S>",
    "\"<?\"",
    "\"?>\"",
    "<AxisChild>",
    "<AxisDescendant>",
    "<AxisParent>",
    "<AxisAttribute>",
    "<AxisSelf>",
    "<AxisDescendantOrSelf>",
    "<AxisAncestor>",
    "<AxisFollowingSibling>",
    "<AxisPrecedingSibling>",
    "<AxisFollowing>",
    "<AxisPreceding>",
    "<AxisNamespace>",
    "<AxisAncestorOrSelf>",
    "<DefineFunction>",
    "\"external\"",
    "\"or\"",
    "\"and\"",
    "\"div\"",
    "\"idiv\"",
    "\"mod\"",
    "\"*\"",
    "\"in\"",
    "<SchemaMode>",
    "<SchemaModeForDeclareValidate>",
    "\"nillable\"",
    "<DeclareValidation>",
    "<SchemaGlobalContextSlash>",
    "<SchemaGlobalTypeName>",
    "<SchemaGlobalContext>",
    "<SchemaContextStepSlash>",
    "<SchemaContextStep>",
    "\"context\"",
    "\"global\"",
    "\"satisfies\"",
    "\"return\"",
    "\"then\"",
    "\"else\"",
    "\"default\"",
    "<DeclareXMLSpace>",
    "<DeclareBaseURI>",
    "\"preserve\"",
    "\"strip\"",
    "\"namespace\"",
    "<DeclareNamespace>",
    "\"to\"",
    "\"where\"",
    "\"collation\"",
    "\"intersect\"",
    "\"union\"",
    "\"except\"",
    "\"as\"",
    "\"at\"",
    "\"case\"",
    "<Instanceof>",
    "<Castable>",
    "<RparAs>",
    "<Item>",
    "<ElementType>",
    "<AttributeType>",
    "<ElementQNameLbrace>",
    "<AttributeQNameLbrace>",
    "<NamespaceNCNameLbrace>",
    "<PINCNameLbrace>",
    "<PILbrace>",
    "<CommentLbrace>",
    "<ElementLbrace>",
    "<AttributeLbrace>",
    "<TextLbrace>",
    "<DeclareCollation>",
    "<DefaultElement>",
    "<DeclareDefaultElement>",
    "<DeclareDefaultFunction>",
    "<Empty>",
    "<ImportSchemaToken>",
    "<ImportModuleToken>",
    "<Nmstart>",
    "<Nmchar>",
    "\"*\"",
    "\"*\"",
    "<NCNameColonStar>",
    "<StarColonNCName>",
    "\"/\"",
    "\"//\"",
    "\"/\"",
    "\"//\"",
    "\"=\"",
    "\"=\"",
    "\"is\"",
    "\"!=\"",
    "\"isnot\"",
    "\"<=\"",
    "\"<<\"",
    "\">=\"",
    "\">>\"",
    "\"eq\"",
    "\"ne\"",
    "\"gt\"",
    "\"ge\"",
    "\"lt\"",
    "\"le\"",
    "\":=\"",
    "\"<\"",
    "\">\"",
    "\"-\"",
    "\"+\"",
    "\"-\"",
    "\"+\"",
    "\"?\"",
    "\"*\"",
    "\"+\"",
    "\"|\"",
    "\"(\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\")\"",
    "\"some\"",
    "\"every\"",
    "\"for\"",
    "\"let\"",
    "<CastAs>",
    "<TreatAs>",
    "<ValidateLbrace>",
    "<ValidateContext>",
    "<ValidateGlobal>",
    "<ValidateSchemaMode>",
    "<Digits>",
    "<DocumentLpar>",
    "<DocumentLparForKindTest>",
    "<DocumentLbrace>",
    "<NodeLpar>",
    "<CommentLpar>",
    "<TextLpar>",
    "<ProcessingInstructionLpar>",
    "<ElementTypeForDocumentTest>",
    "<ElementTypeForKindTest>",
    "<AttributeTypeForKindTest>",
    "<ProcessingInstructionLparForKindTest>",
    "<TextLparForKindTest>",
    "<CommentLparForKindTest>",
    "<NodeLparForKindTest>",
    "<IfLpar>",
    "<TypeswitchLpar>",
    "\",\"",
    "\";\"",
    "\"%%%\"",
    "\",\"",
    "<EscapeQuot>",
    "\"\\\"\"",
    "\"\\\"\"",
    "\".\"",
    "\"..\"",
    "<OrderBy>",
    "<OrderByStable>",
    "\"ascending\"",
    "\"descending\"",
    "<EmptyGreatest>",
    "<EmptyLeast>",
    "<PITarget>",
    "<NCName>",
    "<Prefix>",
    "<LocalPart>",
    "\"$\"",
    "<VarName>",
    "<DefineVariable>",
    "<QNameForSequenceType>",
    "<QNameForItemType>",
    "<ExtensionQName>",
    "<PragmaQName>",
    "<QName>",
    "<NCNameForPrefix>",
    "<NCNameForPI>",
    "\"<![CDATA[\"",
    "<CdataSectionEnd>",
    "<PredefinedEntityRef>",
    "<HexDigits>",
    "<CharRef>",
    "\"<\"",
    "\"<\"",
    "\">\"",
    "\"/>\"",
    "\"</\"",
    "\">\"",
    "\"=\"",
    "<TagQName>",
    "\"{\"",
    "\"{\"",
    "\"{{\"",
    "\"}}\"",
    "\"\\\'\\\'\"",
    "\"\\\'\"",
    "\"\\\'\"",
    "<Char>",
    "<ElementContentChar>",
    "<QuotAttContentChar>",
    "<AposAttContentChar>",
    "<CommentContentChar>",
    "<PIContentChar>",
    "<CDataSectionChar>",
    "\"}\"",
    "<WhitespaceChar>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<Digit>",
    "<Extender>",
  };

}
